services:
  server:
    container_name: bl-server
    image: bloglist-server-dev
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: ./server/
        target: /usr/src/appserver/
    env_file:
      - .env

  app:
    container_name: bl-client
    image: bloglist-client-dev
    build:
      context: ./client
      dockerfile: ./dev.Dockerfile
    volumes:
      - type: bind
        source: ./client/
        target: /usr/src/appclient/
    ports:
      - 3000:3000

  nginx:
    container_name: bl-reverse-proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
