POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": 2.5,
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": 2.5
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": "beans",
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5]
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": 2.5,
    "daily_exercises": 17
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": 2.5,
    "daily_exercises": "Words go here"
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{

}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
    "target": 2.5,
    "daily_exercises": ["string", "number", 47, []]
}






