POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "TestBlog",
    "url": "testblog.com"
}

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "author": "Bad boy who doesnt send required content"
}