POST http://localhost:3001/api/readinglist/
Content-Type: application/json

{
    "blogId": 1,
    "userId": 1
}

###

PUT http://localhost:3001/api/readinglist/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhZG1pbkBhZG1pbi5jb20iLCJpZCI6MSwiaWF0IjoxNjU2MDQxNDEzfQ.tIwocwSrPqaGz7TALAzvxNw4dlIcZPnr-L08VkleWDQ

{
    "isRead": true
}